-- Database: bd_eess

-- DROP DATABASE bd_eess;

CREATE DATABASE bd_eess
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Spanish_Peru.1252'
    LC_CTYPE = 'Spanish_Peru.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;


-- Table: public.specialty

-- DROP TABLE public.specialty;

CREATE TABLE public.specialty
(
    idspecialty integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(80) COLLATE pg_catalog."default",
    CONSTRAINT specialty_pkey PRIMARY KEY (idspecialty)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.specialty
    OWNER to postgres;

-- Table: public.patient

-- DROP TABLE public.patient;

CREATE TABLE public.patient
(
    idpatient integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    firstname character varying(80) COLLATE pg_catalog."default",
    lastname character varying(80) COLLATE pg_catalog."default",
    dni character varying(8) COLLATE pg_catalog."default",
    numberclinicahistory character varying(15) COLLATE pg_catalog."default",
    CONSTRAINT patient_pkey PRIMARY KEY (idpatient)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.patient
    OWNER to postgres;

-- Table: public.doctor

-- DROP TABLE public.doctor;

CREATE TABLE public.doctor
(
    iddoctor integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    firstname character varying(80) COLLATE pg_catalog."default",
    lastname character varying(80) COLLATE pg_catalog."default",
    dni character varying(8) COLLATE pg_catalog."default",
    cmp character varying(50) COLLATE pg_catalog."default",
    idspecialty integer,
    CONSTRAINT doctor_pkey PRIMARY KEY (iddoctor),
    CONSTRAINT fk_idspecialty_doctor FOREIGN KEY (idspecialty)
        REFERENCES public.specialty (idspecialty) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.doctor
    OWNER to postgres;


-- Table: public.medicalconsultation

-- DROP TABLE public.medicalconsultation;

CREATE TABLE public.medicalconsultation
(
    idmedicalconsultation integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    createdate date,
    iddoctor integer,
    idpatient integer,
    CONSTRAINT medicalconsultation_pkey PRIMARY KEY (idmedicalconsultation),
    CONSTRAINT fk_iddoctor_medicalconsultation FOREIGN KEY (iddoctor)
        REFERENCES public.doctor (iddoctor) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT fk_idpatient_medicalconsultation FOREIGN KEY (idpatient)
        REFERENCES public.patient (idpatient) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.medicalconsultation
    OWNER to postgres;

-- Table: public.detailconsultation

-- DROP TABLE public.detailconsultation;

CREATE TABLE public.detailconsultation
(
    iddetailconsultation integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    diagnostic character varying(80) COLLATE pg_catalog."default",
    treatment character varying(100) COLLATE pg_catalog."default",
    idmedicalconsultation integer,
    CONSTRAINT detailconsultation_pkey PRIMARY KEY (iddetailconsultation),
    CONSTRAINT fk_idmedicalconsultation_detailconsultation FOREIGN KEY (idmedicalconsultation)
        REFERENCES public.medicalconsultation (idmedicalconsultation) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.detailconsultation
    OWNER to postgres;
